In [2]:
import pandas as pd

In [6]:
tournamment_df = pd.read_csv("../data/preprocessed_data/processed_champion_stats.csv")

In [7]:
tournamment_df.head(3)

,Year,Tournamment,Champion,G,PB,B,GP,By,W,L,...,CS/M,G.1,G/M,KPAR,KS,GS,As,total_games,%B,%P
0,2018,Spring_Season,Ryze,124,92.5,56,68,10,38,30,...,9.83,11.867532,371.519481,64.6,28.0,20.003896,Mid Laner,134,41.79,50.75
1,2018,Spring_Season,Ryze,124,92.5,56,68,10,38,30,...,9.83,11.867532,371.519481,64.6,28.0,20.003896,Top Laner,134,41.79,50.75
2,2018,Spring_Season,Camille,121,90.3,79,42,15,22,20,...,8.07,12.100000,398.000000,59.7,26.3,21.000000,Top Laner,134,58.96,31.34

Ý nghĩa cột dữ liệu